export const FEATURES_LIST = [
  "TV",
  "Air Conditioning",
  "Balcony",
  "Gym",
  "Garage",
  "Pool",
  "Sauna",
  "Security Guard",
  "Surveillance",
  "Laundry",
  "Wi-Fi",
  "Kitchen Equipment",
  "Furniture",
  "Beds",
  "Bathroom with Bath/Shower",
  "Garden/Patio",
  "Pets Allowed",
  "Utilities Included",
  "Wheelchair Accessible",
  "Elevator",
  "Fireplace",
  "Central Heating",
  "Balcony Furniture",
  "Study/Workspace",
  "Storage Space",
  "Concierge Service",
  "Bike Storage",
  "Rooftop Terrace",
  "Coworking Space",
  "Game Room",
  "Theater Room",
  "Guest Parking",
  "Electric Car Charging",
  "Smart Home Features",
  "Maid Service",
  "On-site Maintenance",
];
